version: 2.1

jobs:
  build:
    docker:
      - image: circleci/php:7.4-node-browsers
    steps:
      - checkout
      - run:
          working_directory: ./backend/php/app
          command: sudo composer self-update --1
      - restore_cache:
          key: composer-v1-{{ checksum "./backend/php/app/composer.lock" }}
      - run:
          working_directory: ./backend/php/app
          command: composer install -n --prefer-dist
      - save_cache:
          key: composer-v1-{{ checksum "./backend/php/app/composer.lock" }}
          paths:
            - ./backend/php/app/vendor
      - run:
          name: php test
          working_directory: ./backend/php/app
          command: vendor/bin/phpunit tests
