module.exports = {
  purge: ['./src/**/*.{js,jsx,ts,tsx}', './public/index.html'],
  darkMode: false, // or 'media' or 'class'
  theme: {
    extend: {
      colors: {
        'gofun': '#edebe8',
        'thin-black': '#434343',
        'secondary': '#dd4b39',
        'orange': 'rgb(226, 147, 0)',
        'thin-orange': 'rgb(255, 230, 183)',
        'brown': '#B76F3B',
        'thin-brown': '#E19661',
        'sky': '#00FFFF',
        'thin-sky': '#BBFFFF',
        'wine': '#93354d',
        'thin-wine': '#dfa0aa',
        'yellow-green': '#C9FF2F',
        'thin-yellow-green': '#E4FF8D',
        'navy': '#000044',
        'thin-navy': '#0000AA',
        'text-hospital': '#dda0dd',
        'bg-hospital': '#fff0f5',
        'burly-wood': '#DEB887',
        'thin-burly-wood': '#FFE4C4',
        'dimgray': 'rgb(100, 99, 99)',
        'thin-dimgray': 'rgb(175, 175, 175)',
        'gold': '#a37f06',
        'thin-gold': '#c1ab05',
        'silver': '#808080',
        'thin-silver': '#C0C0C0',
        'bronze': '#964d04',
        'thin-bronze': '#c47222',
        'button-color-orange': '#ffa45b',
        'amber': 'rgb(254 243 199)',
        'button-color-orange-hover': '#fa812b',
        'button-color-orange-shadow': '#fa8d35',
        'green': 'rgb(0, 185, 46)',
        'thin-green': 'rgb(179, 255, 198)',
        'header-menu': '#fbf6f0',
        'story-set': '#915700',
      },
    },
  },
  variants: {
    extend: {},
  },
  plugins: [],
};
